name: simple_sheet_music
description: A Flutter package for rendering sheet music on canvas. This package provides a simple way to display sheet music in a Flutter application. It includes classes for rendering staffs, measures, clefs, notes, and other music objects.
version: 1.0.0
homepage: https://github.com/Tseku210/music_sheet

environment:
  sdk: ^3.6.0
  flutter: ">=3.27.0"

workspace:
  - packages/score_model

dependencies:
  flutter:
    sdk: flutter
  flutter_midi_pro: ^4.0.4
  svg_path_parser: ^1.1.2
  uuid: ^4.3.3
  xml: ">=6.5.0 <8.0.0"

dev_dependencies:
  flutter_test:
    sdk: flutter
  path_provider_platform_interface: ^2.1.3
  pedantic_mono: ^1.38.1
  plugin_platform_interface: ^2.1.8

flutter:
  assets:
    - assets/Bravura.svg
    - assets/bravura_metadata.json
    - assets/Petaluma.svg
    - assets/petaluma_metadata.json
