// GENERATED by tool/generate_bravura.dart from Bravura 1.392.
// Do not edit.

import 'geometry.dart';
import 'glyphs.dart';

const bravuraDefaults = EngravingDefaults(
  arrowShaftThickness: 0.16,
  barlineSeparation: 0.4,
  beamSpacing: 0.25,
  beamThickness: 0.5,
  bracketThickness: 0.5,
  dashedBarlineDashLength: 0.5,
  dashedBarlineGapLength: 0.25,
  dashedBarlineThickness: 0.16,
  hBarThickness: 1,
  hairpinThickness: 0.16,
  legerLineExtension: 0.4,
  legerLineThickness: 0.16,
  lyricLineThickness: 0.16,
  octaveLineThickness: 0.16,
  pedalLineThickness: 0.16,
  repeatBarlineDotSeparation: 0.16,
  repeatEndingLineThickness: 0.16,
  slurEndpointThickness: 0.1,
  slurMidpointThickness: 0.22,
  staffLineThickness: 0.13,
  stemThickness: 0.12,
  subBracketThickness: 0.16,
  textEnclosureThickness: 0.16,
  thickBarlineThickness: 0.5,
  thinBarlineThickness: 0.16,
  tieEndpointThickness: 0.1,
  tieMidpointThickness: 0.22,
  tupletBracketThickness: 0.16,
);

const bravuraGlyphs = <Glyph, GlyphMetrics>{
  Glyph.gClef: GlyphMetrics(
    box: Box(0, -4.392, 2.684, 2.632),
    advance: 2.684,
  ),
  Glyph.gClef8vb: GlyphMetrics(
    box: Box(0, -4.392, 2.684, 3.512),
    advance: 2.656,
  ),
  Glyph.gClef8va: GlyphMetrics(
    box: Box(0, -5.28, 2.684, 2.632),
    advance: 2.684,
  ),
  Glyph.cClef: GlyphMetrics(
    box: Box(0, -2.024, 2.796, 2.024),
    advance: 2.796,
  ),
  Glyph.fClef: GlyphMetrics(
    box: Box(-0.02, -1.048, 2.736, 2.54),
    advance: 2.736,
  ),
  Glyph.fClef8vb: GlyphMetrics(
    box: Box(-0.02, -1.048, 2.736, 2.976),
    advance: 2.736,
  ),
  Glyph.unpitchedPercussionClef1: GlyphMetrics(
    box: Box(0, -1, 1.528, 1),
    advance: 1.528,
  ),
  Glyph.gClefChange: GlyphMetrics(
    box: Box(0, -2.828, 1.76, 1.82),
    advance: 1.76,
  ),
  Glyph.cClefChange: GlyphMetrics(
    box: Box(0, -1.328, 2.024, 1.328),
    advance: 2.024,
  ),
  Glyph.fClefChange: GlyphMetrics(
    box: Box(-0.06, -0.68, 1.852, 1.656),
    advance: 1.848,
  ),
  Glyph.accidentalFlat: GlyphMetrics(
    box: Box(0, -1.756, 0.904, 0.7),
    advance: 0.904,
    anchors: {
      GlyphAnchor.cutOutNE: SpPoint(0.252, -0.656),
      GlyphAnchor.cutOutSE: SpPoint(0.504, 0.476),
    },
  ),
  Glyph.accidentalNatural: GlyphMetrics(
    box: Box(0, -1.364, 0.672, 1.34),
    advance: 0.672,
    anchors: {
      GlyphAnchor.cutOutNE: SpPoint(0.192, -0.776),
      GlyphAnchor.cutOutSW: SpPoint(0.476, 0.828),
    },
  ),
  Glyph.accidentalSharp: GlyphMetrics(
    box: Box(0, -1.4, 0.996, 1.392),
    advance: 0.996,
    anchors: {
      GlyphAnchor.cutOutNE: SpPoint(0.84, -0.896),
      GlyphAnchor.cutOutNW: SpPoint(0.144, -0.568),
      GlyphAnchor.cutOutSE: SpPoint(0.84, 0.596),
      GlyphAnchor.cutOutSW: SpPoint(0.144, 0.896),
    },
  ),
  Glyph.accidentalDoubleSharp: GlyphMetrics(
    box: Box(0, -0.508, 0.988, 0.5),
    advance: 1,
  ),
  Glyph.accidentalDoubleFlat: GlyphMetrics(
    box: Box(0, -1.748, 1.644, 0.7),
    advance: 1.652,
    anchors: {
      GlyphAnchor.cutOutNE: SpPoint(0.988, -0.644),
      GlyphAnchor.cutOutSE: SpPoint(1.336, 0.396),
    },
  ),
  Glyph.accidentalParensLeft: GlyphMetrics(
    box: Box(0, -0.988, 0.564, 0.992),
    advance: 0.564,
  ),
  Glyph.accidentalParensRight: GlyphMetrics(
    box: Box(0, -0.988, 0.564, 0.992),
    advance: 0.564,
  ),
  Glyph.accidentalQuarterToneFlatStein: GlyphMetrics(
    box: Box(0.004, -1.756, 0.908, 0.7),
    advance: 0.908,
    anchors: {
      GlyphAnchor.cutOutNW: SpPoint(0.628, -0.676),
      GlyphAnchor.cutOutSW: SpPoint(0.336, 0.428),
    },
  ),
  Glyph.accidentalThreeQuarterTonesFlatZimmermann: GlyphMetrics(
    box: Box(0.004, -1.756, 1.864, 0.7),
    advance: 1.864,
    anchors: {
      GlyphAnchor.cutOutNE: SpPoint(1.22, -0.668),
      GlyphAnchor.cutOutNW: SpPoint(0.636, -0.668),
    },
  ),
  Glyph.accidentalQuarterToneSharpStein: GlyphMetrics(
    box: Box(0, -1.228, 0.716, 1.412),
    advance: 0.716,
    anchors: {
      GlyphAnchor.cutOutNE: SpPoint(0.476, -0.748),
      GlyphAnchor.cutOutNW: SpPoint(0.224, -0.604),
      GlyphAnchor.cutOutSE: SpPoint(0.492, 0.8),
      GlyphAnchor.cutOutSW: SpPoint(0.224, 0.92),
    },
  ),
  Glyph.accidentalThreeQuarterTonesSharpStein: GlyphMetrics(
    box: Box(0.012, -1.476, 1.268, 1.388),
    advance: 1.268,
    anchors: {
      GlyphAnchor.cutOutNE: SpPoint(1.128, -1),
      GlyphAnchor.cutOutNW: SpPoint(0.144, -0.604),
      GlyphAnchor.cutOutSE: SpPoint(1.128, 0.5),
      GlyphAnchor.cutOutSW: SpPoint(0.144, 0.896),
    },
  ),
  Glyph.accidentalNarrowReversedFlatAndFlat: GlyphMetrics(
    box: Box(0, -1.684, 1.656, 0.776),
    advance: 1.656,
    anchors: {
      GlyphAnchor.cutOutNE: SpPoint(0.988, -0.744),
      GlyphAnchor.cutOutNW: SpPoint(0.444, -0.744),
      GlyphAnchor.cutOutSE: SpPoint(1.352, 0.456),
      GlyphAnchor.cutOutSW: SpPoint(0.196, 0.456),
    },
  ),
  Glyph.accidentalQuarterToneFlatArrowUp: GlyphMetrics(
    box: Box(-0.168, -2.316, 0.992, 0.708),
    advance: 0.992,
    anchors: {
      GlyphAnchor.cutOutNE: SpPoint(0.604, -0.664),
      GlyphAnchor.cutOutSE: SpPoint(0.62, 0.452),
    },
  ),
  Glyph.accidentalThreeQuarterTonesFlatArrowDown: GlyphMetrics(
    box: Box(-0.156, -1.768, 1.004, 1.672),
    advance: 1.004,
    anchors: {
      GlyphAnchor.cutOutNE: SpPoint(0.356, -0.648),
      GlyphAnchor.cutOutNW: SpPoint(0.032, 0.8),
      GlyphAnchor.cutOutSE: SpPoint(0.648, 0.5),
    },
  ),
  Glyph.accidentalQuarterToneSharpNaturalArrowUp: GlyphMetrics(
    box: Box(-0.104, -2.188, 0.848, 1.36),
    advance: 0.848,
    anchors: {
      GlyphAnchor.cutOutSW: SpPoint(0.616, 0.868),
    },
  ),
  Glyph.accidentalQuarterToneFlatNaturalArrowDown: GlyphMetrics(
    box: Box(0.012, -1.344, 1, 2.172),
    advance: 0.684,
    anchors: {
      GlyphAnchor.cutOutNE: SpPoint(0.232, -0.788),
    },
  ),
  Glyph.accidentalThreeQuarterTonesSharpArrowUp: GlyphMetrics(
    box: Box(0, -2.12, 1.1, 1.388),
    advance: 0.996,
    anchors: {
      GlyphAnchor.cutOutNW: SpPoint(0.272, -1.304),
      GlyphAnchor.cutOutSE: SpPoint(0.86, 0.584),
      GlyphAnchor.cutOutSW: SpPoint(0.132, 0.888),
    },
  ),
  Glyph.accidentalQuarterToneSharpArrowDown: GlyphMetrics(
    box: Box(-0.112, -1.396, 0.996, 2.136),
    advance: 0.996,
    anchors: {
      GlyphAnchor.cutOutNE: SpPoint(0.856, -0.908),
      GlyphAnchor.cutOutNW: SpPoint(0.132, -0.608),
      GlyphAnchor.cutOutSE: SpPoint(0.856, 0.588),
    },
  ),
  Glyph.noteheadDoubleWhole: GlyphMetrics(
    box: Box(0, -0.62, 2.396, 0.62),
    advance: 2.396,
    anchors: {
      GlyphAnchor.noteheadOrigin: SpPoint(0.36, 0),
    },
  ),
  Glyph.noteheadDoubleWholeSquare: GlyphMetrics(
    box: Box(0, -0.792, 1.664, 0.76),
    advance: 1.664,
  ),
  Glyph.noteheadWhole: GlyphMetrics(
    box: Box(0, -0.5, 1.688, 0.5),
    advance: 1.688,
    anchors: {
      GlyphAnchor.cutOutNW: SpPoint(0.172, -0.332),
      GlyphAnchor.cutOutSE: SpPoint(1.532, 0.364),
    },
  ),
  Glyph.noteheadHalf: GlyphMetrics(
    box: Box(0, -0.5, 1.18, 0.5),
    advance: 1.18,
    anchors: {
      GlyphAnchor.cutOutNW: SpPoint(0.204, -0.296),
      GlyphAnchor.cutOutSE: SpPoint(0.98, 0.3),
      GlyphAnchor.splitStemDownNE: SpPoint(0.956, 0.3),
      GlyphAnchor.splitStemDownNW: SpPoint(0.128, 0.428),
      GlyphAnchor.splitStemUpSE: SpPoint(1.108, -0.372),
      GlyphAnchor.splitStemUpSW: SpPoint(0.328, -0.38),
      GlyphAnchor.stemDownNW: SpPoint(0, 0.168),
      GlyphAnchor.stemUpSE: SpPoint(1.18, -0.168),
    },
  ),
  Glyph.noteheadBlack: GlyphMetrics(
    box: Box(0, -0.5, 1.18, 0.5),
    advance: 1.18,
    anchors: {
      GlyphAnchor.cutOutNW: SpPoint(0.208, -0.3),
      GlyphAnchor.cutOutSE: SpPoint(0.94, 0.296),
      GlyphAnchor.splitStemDownNE: SpPoint(0.968, 0.248),
      GlyphAnchor.splitStemDownNW: SpPoint(0.12, 0.416),
      GlyphAnchor.splitStemUpSE: SpPoint(1.092, -0.392),
      GlyphAnchor.splitStemUpSW: SpPoint(0.312, -0.356),
      GlyphAnchor.stemDownNW: SpPoint(0, 0.168),
      GlyphAnchor.stemUpSE: SpPoint(1.18, -0.168),
    },
  ),
  Glyph.noteheadXDoubleWhole: GlyphMetrics(
    box: Box(0, -0.62, 2.184, 0.62),
    advance: 2.184,
    anchors: {
      GlyphAnchor.noteheadOrigin: SpPoint(0.348, 0),
    },
  ),
  Glyph.noteheadXWhole: GlyphMetrics(
    box: Box(0, -0.5, 1.508, 0.5),
    advance: 1.508,
  ),
  Glyph.noteheadXHalf: GlyphMetrics(
    box: Box(0, -0.5, 1.336, 0.5),
    advance: 1.336,
    anchors: {
      GlyphAnchor.stemDownNW: SpPoint(0, 0.412),
      GlyphAnchor.stemUpSE: SpPoint(1.336, -0.412),
    },
  ),
  Glyph.noteheadXBlack: GlyphMetrics(
    box: Box(0, -0.5, 1.16, 0.5),
    advance: 1.16,
    anchors: {
      GlyphAnchor.stemDownNW: SpPoint(0, 0.44),
      GlyphAnchor.stemUpSE: SpPoint(1.16, -0.444),
    },
  ),
  Glyph.noteheadCircleXDoubleWhole: GlyphMetrics(
    box: Box(0, -0.62, 1.688, 0.62),
    advance: 1.688,
    anchors: {
      GlyphAnchor.noteheadOrigin: SpPoint(0.352, 0),
    },
  ),
  Glyph.noteheadCircleXWhole: GlyphMetrics(
    box: Box(0, -0.5, 0.996, 0.5),
    advance: 0.996,
  ),
  Glyph.noteheadCircleXHalf: GlyphMetrics(
    box: Box(0, -0.5, 1, 0.5),
    advance: 1,
    anchors: {
      GlyphAnchor.stemDownNW: SpPoint.zero,
      GlyphAnchor.stemUpSE: SpPoint(1, 0),
    },
  ),
  Glyph.noteheadCircleX: GlyphMetrics(
    box: Box(0, -0.5, 0.996, 0.5),
    advance: 0.996,
    anchors: {
      GlyphAnchor.stemDownNW: SpPoint.zero,
      GlyphAnchor.stemUpSE: SpPoint(0.996, 0),
    },
  ),
  Glyph.noteheadTriangleUpDoubleWhole: GlyphMetrics(
    box: Box(0, -0.62, 1.932, 0.62),
    advance: 1.932,
    anchors: {
      GlyphAnchor.noteheadOrigin: SpPoint(0.34, 0),
    },
  ),
  Glyph.noteheadTriangleUpWhole: GlyphMetrics(
    box: Box(0, -0.5, 1.276, 0.5),
    advance: 1.276,
  ),
  Glyph.noteheadTriangleUpHalf: GlyphMetrics(
    box: Box(0, -0.5, 1.14, 0.5),
    advance: 1.14,
    anchors: {
      GlyphAnchor.stemDownNW: SpPoint(0, 0.46),
      GlyphAnchor.stemUpSE: SpPoint(1.14, 0.46),
    },
  ),
  Glyph.noteheadTriangleUpBlack: GlyphMetrics(
    box: Box(0, -0.5, 1.172, 0.5),
    advance: 1.172,
    anchors: {
      GlyphAnchor.stemDownNW: SpPoint(0, 0.5),
      GlyphAnchor.stemUpSE: SpPoint(1.172, 0.5),
    },
  ),
  Glyph.noteheadDiamondDoubleWhole: GlyphMetrics(
    box: Box(0, -0.62, 1.728, 0.62),
    advance: 1.728,
    anchors: {
      GlyphAnchor.noteheadOrigin: SpPoint(0.324, 0),
    },
  ),
  Glyph.noteheadDiamondWhole: GlyphMetrics(
    box: Box(0, -0.5, 1.08, 0.5),
    advance: 1.08,
  ),
  Glyph.noteheadDiamondHalf: GlyphMetrics(
    box: Box(0, -0.5, 1.004, 0.5),
    advance: 1.004,
    anchors: {
      GlyphAnchor.stemDownNW: SpPoint.zero,
      GlyphAnchor.stemUpSE: SpPoint(1.004, 0),
    },
  ),
  Glyph.noteheadDiamondBlack: GlyphMetrics(
    box: Box(0, -0.5, 1, 0.5),
    advance: 1,
    anchors: {
      GlyphAnchor.stemDownNW: SpPoint.zero,
      GlyphAnchor.stemUpSE: SpPoint(1, 0),
    },
  ),
  Glyph.noteheadDiamondWhite: GlyphMetrics(
    box: Box(0, -0.5, 1, 0.5),
    advance: 1,
    anchors: {
      GlyphAnchor.stemDownNW: SpPoint.zero,
      GlyphAnchor.stemUpSE: SpPoint(1, 0),
    },
  ),
  Glyph.noteheadSlashWhiteDoubleWhole: GlyphMetrics(
    box: Box(0, -1, 4.644, 1),
    advance: 4.644,
  ),
  Glyph.noteheadSlashWhiteWhole: GlyphMetrics(
    box: Box(0, -1, 3.92, 1),
    advance: 3.92,
  ),
  Glyph.noteheadSlashWhiteHalf: GlyphMetrics(
    box: Box(0, -1, 3.12, 1),
    advance: 3.12,
    anchors: {
      GlyphAnchor.stemDownNW: SpPoint(0, 1),
      GlyphAnchor.stemUpSE: SpPoint(3.12, -1),
    },
  ),
  Glyph.noteheadSlashHorizontalEnds: GlyphMetrics(
    box: Box(0, -1, 2.12, 1),
    advance: 2.124,
    anchors: {
      GlyphAnchor.stemDownNW: SpPoint(0, 1),
      GlyphAnchor.stemUpSE: SpPoint(2.12, -1),
    },
  ),
  Glyph.augmentationDot: GlyphMetrics(
    box: Box(0, -0.2, 0.4, 0.2),
    advance: 0.4,
  ),
  Glyph.stem: GlyphMetrics(
    box: Box(-0.06, -3.5, 0.06, 0),
    advance: 0.06,
  ),
  Glyph.tremolo1: GlyphMetrics(
    box: Box(-0.6, -0.376, 0.6, 0.372),
    advance: 0.6,
  ),
  Glyph.tremolo2: GlyphMetrics(
    box: Box(-0.604, -0.748, 0.596, 0.748),
    advance: 0.596,
  ),
  Glyph.tremolo3: GlyphMetrics(
    box: Box(-0.6, -1.112, 0.6, 1.12),
    advance: 0.6,
  ),
  Glyph.tremolo4: GlyphMetrics(
    box: Box(-0.6, -1.496, 0.6, 1.48),
    advance: 0.596,
  ),
  Glyph.flag8thUp: GlyphMetrics(
    box: Box(0, -0.03521239682756091, 1.056, 3.240768470618394),
    advance: 1.056,
    anchors: {
      GlyphAnchor.graceNoteSlashNE: SpPoint(1.284, 0.796),
      GlyphAnchor.graceNoteSlashSW: SpPoint(-0.644, 2.456),
      GlyphAnchor.stemUpNW: SpPoint(0, 0.04),
    },
  ),
  Glyph.flag8thDown: GlyphMetrics(
    box: Box(0, -3.232896633157715, 1.224, 0.0575672),
    advance: 1.224,
    anchors: {
      GlyphAnchor.graceNoteSlashNW: SpPoint(-0.596, -2.168),
      GlyphAnchor.graceNoteSlashSE: SpPoint(1.328, -0.628),
      GlyphAnchor.stemDownSW: SpPoint(0, -0.132),
    },
  ),
  Glyph.flag16thUp: GlyphMetrics(
    box: Box(0, -0.008, 1.116, 3.252),
    advance: 1.116,
    anchors: {
      GlyphAnchor.stemUpNW: SpPoint(0, 0.088),
    },
  ),
  Glyph.flag16thDown: GlyphMetrics(
    box: Box(
      -0.000019418183745617774,
      -3.2480256,
      1.1635806326044895,
      0.03601094374150052,
    ),
    advance: 1.168,
    anchors: {
      GlyphAnchor.stemDownSW: SpPoint(0, -0.128),
    },
  ),
  Glyph.flag32ndUp: GlyphMetrics(
    box: Box(0, -0.596, 1.044, 3.248),
    advance: 1.048,
    anchors: {
      GlyphAnchor.stemUpNW: SpPoint(0, -0.376),
    },
  ),
  Glyph.flag32ndDown: GlyphMetrics(
    box: Box(0, -3.248, 1.092, 0.687477099907407),
    advance: 1.096,
    anchors: {
      GlyphAnchor.stemDownSW: SpPoint(0, 0.448),
    },
  ),
  Glyph.flag64thUp: GlyphMetrics(
    box: Box(0, -1.387108, 1.044, 3.248),
    advance: 1.048,
    anchors: {
      GlyphAnchor.stemUpNW: SpPoint(0, -1.172),
    },
  ),
  Glyph.flag64thDown: GlyphMetrics(
    box: Box(0, -3.248, 1.092, 1.5040263329569774),
    advance: 1.1,
    anchors: {
      GlyphAnchor.stemDownSW: SpPoint(0, 1.244),
    },
  ),
  Glyph.flag128thUp: GlyphMetrics(
    box: Box(0, -2.1320003247537183, 1.044, 3.248),
    advance: 1.036,
    anchors: {
      GlyphAnchor.stemUpNW: SpPoint(0, -1.9),
    },
  ),
  Glyph.flag128thDown: GlyphMetrics(
    box: Box(0, -3.248, 1.092, 2.320034471092627),
    advance: 1.1,
    anchors: {
      GlyphAnchor.stemDownSW: SpPoint(0, 2.076),
    },
  ),
  Glyph.graceNoteSlashStemUp: GlyphMetrics(
    box: Box(0, -1.604, 2.02, 0),
    advance: 2.02,
  ),
  Glyph.graceNoteSlashStemDown: GlyphMetrics(
    box: Box(0, 0, 2.02, 1.604),
    advance: 2.02,
  ),
  Glyph.graceNoteAcciaccaturaStemUp: GlyphMetrics(
    box: Box(0, -2.096, 1.428, 0.332),
    advance: 1.428,
  ),
  Glyph.graceNoteAcciaccaturaStemDown: GlyphMetrics(
    box: Box(-0.336, -0.332, 0.78, 2.1),
    advance: 0.78,
  ),
  Glyph.restDoubleWhole: GlyphMetrics(
    box: Box(0, -1, 0.5, 0),
    advance: 0.504,
  ),
  Glyph.restWhole: GlyphMetrics(
    box: Box(0, -0.036, 1.128, 0.54),
    advance: 1.132,
  ),
  Glyph.restHalf: GlyphMetrics(
    box: Box(0, -0.568, 1.128, 0.008),
    advance: 1.132,
  ),
  Glyph.restQuarter: GlyphMetrics(
    box: Box(0.004, -1.492, 1.08, 1.5),
    advance: 1.08,
  ),
  Glyph.rest8th: GlyphMetrics(
    box: Box(0, -0.696, 0.988, 1.004),
    advance: 1,
  ),
  Glyph.rest16th: GlyphMetrics(
    box: Box(0, -0.716, 1.28, 2),
    advance: 1.28,
  ),
  Glyph.rest32nd: GlyphMetrics(
    box: Box(0, -1.704, 1.452, 2),
    advance: 1.452,
  ),
  Glyph.rest64th: GlyphMetrics(
    box: Box(0, -1.72, 1.692, 3.012),
    advance: 1.696,
  ),
  Glyph.rest128th: GlyphMetrics(
    box: Box(0, -2.756, 1.94, 3),
    advance: 1.94,
  ),
  Glyph.restHBar: GlyphMetrics(
    box: Box(0, -1.044, 3.128, 1.084),
    advance: 3.136,
  ),
  Glyph.restHBarLeft: GlyphMetrics(
    box: Box(0, -1.048, 1.5, 1.08),
    advance: 1.508,
  ),
  Glyph.restHBarMiddle: GlyphMetrics(
    box: Box(-0.108, -0.384, 1.42, 0.416),
    advance: 1.312,
  ),
  Glyph.restHBarRight: GlyphMetrics(
    box: Box(0, -1.048, 1.5, 1.08),
    advance: 1.508,
  ),
  Glyph.restDoubleWholeLegerLine: GlyphMetrics(
    box: Box(0, -1.056, 1.176, 0.1),
    advance: 1.176,
  ),
  Glyph.restWholeLegerLine: GlyphMetrics(
    box: Box(-0.468, -0.08, 1.596, 0.54),
    advance: 1.128,
  ),
  Glyph.restHalfLegerLine: GlyphMetrics(
    box: Box(-0.468, -0.568, 1.596, 0.052),
    advance: 1.128,
  ),
  Glyph.timeSig0: GlyphMetrics(
    box: Box(0.08, -1.004, 1.8, 1),
    advance: 1.88,
  ),
  Glyph.timeSig1: GlyphMetrics(
    box: Box(0.08, -1.004, 1.256, 1),
    advance: 1.336,
  ),
  Glyph.timeSig2: GlyphMetrics(
    box: Box(0.08, -1.016, 1.704, 1.028),
    advance: 1.784,
  ),
  Glyph.timeSig3: GlyphMetrics(
    box: Box(0.08, -0.996, 1.604, 1.004),
    advance: 1.684,
  ),
  Glyph.timeSig4: GlyphMetrics(
    box: Box(0.08, -1.004, 1.8, 1),
    advance: 1.88,
  ),
  Glyph.timeSig5: GlyphMetrics(
    box: Box(0.08, -0.984, 1.532, 1.004),
    advance: 1.612,
  ),
  Glyph.timeSig6: GlyphMetrics(
    box: Box(0.08, -1.004, 1.656, 0.996),
    advance: 1.736,
  ),
  Glyph.timeSig7: GlyphMetrics(
    box: Box(0.08, -0.996, 1.684, 1),
    advance: 1.764,
  ),
  Glyph.timeSig8: GlyphMetrics(
    box: Box(0.08, -1.036, 1.664, 1.036),
    advance: 1.744,
  ),
  Glyph.timeSig9: GlyphMetrics(
    box: Box(0.08, -1.004, 1.656, 0.996),
    advance: 1.736,
  ),
  Glyph.timeSigCommon: GlyphMetrics(
    box: Box(0.02, -1.004, 1.696, 0.996),
    advance: 1.696,
  ),
  Glyph.timeSigCutCommon: GlyphMetrics(
    box: Box(0, -1.444, 1.672, 1.436),
    advance: 1.668,
  ),
  Glyph.timeSigPlus: GlyphMetrics(
    box: Box(-0.004, -1, 1.996, 1),
    advance: 2,
  ),
  Glyph.timeSigPlusSmall: GlyphMetrics(
    box: Box(-0.00204, -0.49, 1.01796, 0.53),
    advance: 1.016,
  ),
  Glyph.tuplet0: GlyphMetrics(
    box: Box(-0.001204330173715796, -1.5, 1.2731041262817027, 0.032),
    advance: 1.276,
  ),
  Glyph.tuplet1: GlyphMetrics(
    box: Box(0.04, -1.488, 1.024, 0),
    advance: 0.984,
  ),
  Glyph.tuplet2: GlyphMetrics(
    box: Box(0.04, -1.5, 1.316, 0.024),
    advance: 1.276,
  ),
  Glyph.tuplet3: GlyphMetrics(
    box: Box(0.04, -1.5, 1.224, 0.032),
    advance: 1.184,
  ),
  Glyph.tuplet4: GlyphMetrics(
    box: Box(0.04, -1.488, 1.252, 0),
    advance: 1.212,
  ),
  Glyph.tuplet5: GlyphMetrics(
    box: Box(0.04, -1.492, 1.308, 0.032),
    advance: 1.268,
  ),
  Glyph.tuplet6: GlyphMetrics(
    box: Box(0.04105974105482295, -1.5, 1.256, 0.032),
    advance: 1.216,
  ),
  Glyph.tuplet7: GlyphMetrics(
    box: Box(0.12, -1.488, 1.332, 0.016),
    advance: 1.212,
  ),
  Glyph.tuplet8: GlyphMetrics(
    box: Box(0.04, -1.5, 1.292, 0.032),
    advance: 1.252,
  ),
  Glyph.tuplet9: GlyphMetrics(
    box: Box(0.04, -1.5, 1.254940258945177, 0.032),
    advance: 1.216,
  ),
  Glyph.tupletColon: GlyphMetrics(
    box: Box(0.04, -1.072, 0.484, -0.232),
    advance: 0.444,
  ),
  Glyph.dynamicPiano: GlyphMetrics(
    box: Box(-0.356, -1.096, 1.464, 0.568),
    advance: 1.46,
    anchors: {
      GlyphAnchor.opticalCenter: SpPoint(1.22, 0),
    },
  ),
  Glyph.dynamicMezzo: GlyphMetrics(
    box: Box(-0.08, -1.096, 1.784, 0.04),
    advance: 1.748,
    anchors: {
      GlyphAnchor.opticalCenter: SpPoint(0.872, 0),
    },
  ),
  Glyph.dynamicForte: GlyphMetrics(
    box: Box(-0.564, -1.776, 1.456, 0.608),
    advance: 1.456,
    anchors: {
      GlyphAnchor.opticalCenter: SpPoint(1.256, 0),
    },
  ),
  Glyph.dynamicRinforzando: GlyphMetrics(
    box: Box(-0.08, -1.096, 1.108, 0),
    advance: 1.108,
    anchors: {
      GlyphAnchor.opticalCenter: SpPoint(0.612, 0),
    },
  ),
  Glyph.dynamicSforzando: GlyphMetrics(
    box: Box(0, -1.092, 0.916, 0.04),
    advance: 0.916,
    anchors: {
      GlyphAnchor.opticalCenter: SpPoint(0.444, 0),
    },
  ),
  Glyph.dynamicZ: GlyphMetrics(
    box: Box(-0.12, -1.072, 0.976, 0.04),
    advance: 0.976,
    anchors: {
      GlyphAnchor.opticalCenter: SpPoint(0.5, 0),
    },
  ),
  Glyph.dynamicPPPP: GlyphMetrics(
    box: Box(-0.408, -1.096, 5.672, 0.568),
    advance: 5.668,
    anchors: {
      GlyphAnchor.opticalCenter: SpPoint(3.004, 0),
    },
  ),
  Glyph.dynamicPPP: GlyphMetrics(
    box: Box(-0.368, -1.096, 4.292, 0.568),
    advance: 4.288,
    anchors: {
      GlyphAnchor.opticalCenter: SpPoint(2.368, 0),
    },
  ),
  Glyph.dynamicPP: GlyphMetrics(
    box: Box(-0.328, -1.096, 2.912, 0.568),
    advance: 2.908,
    anchors: {
      GlyphAnchor.opticalCenter: SpPoint(1.708, 0),
    },
  ),
  Glyph.dynamicMP: GlyphMetrics(
    box: Box(-0.08, -1.096, 3.3, 0.568),
    advance: 3.304,
    anchors: {
      GlyphAnchor.opticalCenter: SpPoint(1.848, 0),
    },
  ),
  Glyph.dynamicMF: GlyphMetrics(
    box: Box(-0.08, -1.724, 3.272, 0.66),
    advance: 3.188,
    anchors: {
      GlyphAnchor.opticalCenter: SpPoint(1.796, 0),
    },
  ),
  Glyph.dynamicFF: GlyphMetrics(
    box: Box(-0.54, -1.776, 2.44, 0.608),
    advance: 2.436,
    anchors: {
      GlyphAnchor.opticalCenter: SpPoint(1.852, 0),
    },
  ),
  Glyph.dynamicFFF: GlyphMetrics(
    box: Box(-0.62, -1.776, 3.32, 0.608),
    advance: 3.324,
    anchors: {
      GlyphAnchor.opticalCenter: SpPoint(2.472, 0),
    },
  ),
  Glyph.dynamicFFFF: GlyphMetrics(
    box: Box(-0.62, -1.776, 4.28, 0.608),
    advance: 4.28,
    anchors: {
      GlyphAnchor.opticalCenter: SpPoint(2.824, 0),
    },
  ),
  Glyph.dynamicFortePiano: GlyphMetrics(
    box: Box(-0.564, -1.776, 2.476, 0.608),
    advance: 2.476,
    anchors: {
      GlyphAnchor.opticalCenter: SpPoint(1.5, 0),
    },
  ),
  Glyph.dynamicSforzando1: GlyphMetrics(
    box: Box(0, -1.776, 2.416, 0.608),
    advance: 2.416,
    anchors: {
      GlyphAnchor.opticalCenter: SpPoint(1.3, 0),
    },
  ),
  Glyph.dynamicSforzato: GlyphMetrics(
    box: Box(0, -1.776, 2.932, 0.608),
    advance: 2.928,
    anchors: {
      GlyphAnchor.opticalCenter: SpPoint(1.76, 0),
    },
  ),
  Glyph.dynamicRinforzando2: GlyphMetrics(
    box: Box(-0.08, -1.776, 2.976, 0.608),
    advance: 2.976,
    anchors: {
      GlyphAnchor.opticalCenter: SpPoint(2.084, 0),
    },
  ),
  Glyph.articAccentAbove: GlyphMetrics(
    box: Box(0, -0.98, 1.356, -0.004),
    advance: 1.356,
  ),
  Glyph.articAccentBelow: GlyphMetrics(
    box: Box(0, 0, 1.356, 0.976),
    advance: 1.356,
  ),
  Glyph.articStaccatoAbove: GlyphMetrics(
    box: Box(0, -0.336, 0.336, 0),
    advance: 0.336,
  ),
  Glyph.articStaccatoBelow: GlyphMetrics(
    box: Box(0, 0, 0.336, 0.336),
    advance: 0.336,
  ),
  Glyph.articTenutoAbove: GlyphMetrics(
    box: Box(-0.004, -0.192, 1.352, 0),
    advance: 1.352,
  ),
  Glyph.articTenutoBelow: GlyphMetrics(
    box: Box(-0.004, 0, 1.352, 0.192),
    advance: 1.352,
  ),
  Glyph.articStaccatissimoAbove: GlyphMetrics(
    box: Box(0.004, -1.172, 0.4, 0.008),
    advance: 0.408,
  ),
  Glyph.articStaccatissimoBelow: GlyphMetrics(
    box: Box(0.004, 0, 0.4, 1.18),
    advance: 0.408,
  ),
  Glyph.articMarcatoAbove: GlyphMetrics(
    box: Box(-0.004, -1.012, 0.94, 0.004),
    advance: 0.944,
  ),
  Glyph.articMarcatoBelow: GlyphMetrics(
    box: Box(-0.004, 0, 0.94, 1.016),
    advance: 0.944,
  ),
  Glyph.fermataAbove: GlyphMetrics(
    box: Box(0.012, -1.316, 2.42, 0.012),
    advance: 2.42,
  ),
  Glyph.fermataBelow: GlyphMetrics(
    box: Box(0.012, 0, 2.42, 1.328),
    advance: 2.42,
  ),
  Glyph.stringsHarmonic: GlyphMetrics(
    box: Box(0, -0.8, 0.8, 0),
    advance: 0.8,
  ),
  Glyph.ornamentTrill: GlyphMetrics(
    box: Box(0, -1.56, 2.084, 0.04),
    advance: 2.084,
  ),
  Glyph.ornamentTurn: GlyphMetrics(
    box: Box(0, -0.872, 1.84, 0),
    advance: 1.84,
  ),
  Glyph.ornamentTurnInverted: GlyphMetrics(
    box: Box(-0.012, -0.872, 1.828, 0),
    advance: 1.828,
  ),
  Glyph.ornamentShortTrill: GlyphMetrics(
    box: Box(0, -0.98, 2.9, 0),
    advance: 2.92,
  ),
  Glyph.ornamentMordent: GlyphMetrics(
    box: Box(0.004, -1.276, 2.916, 0.292),
    advance: 2.916,
  ),
  Glyph.wiggleTrill: GlyphMetrics(
    box: Box(-0.144, -0.836, 1.08, -0.392),
    advance: 0.948,
    anchors: {
      GlyphAnchor.repeatOffset: SpPoint(0.948, 0),
    },
  ),
  Glyph.wiggleGlissando: GlyphMetrics(
    box: Box(-0.1, -0.444, 1.124, 0),
    advance: 0.96,
    anchors: {
      GlyphAnchor.repeatOffset: SpPoint(0.96, 0),
    },
  ),
  Glyph.stringsDownBow: GlyphMetrics(
    box: Box(0, -1.272, 1.248, 0),
    advance: 1.248,
  ),
  Glyph.stringsUpBow: GlyphMetrics(
    box: Box(0.004, -1.98, 0.996, -0.004),
    advance: 1,
  ),
  Glyph.fingering0: GlyphMetrics(
    box: Box(0.08, -1.004, 0.94, 0.004),
    advance: 1.02,
  ),
  Glyph.fingering1: GlyphMetrics(
    box: Box(0.08, -1.016, 0.548, 0),
    advance: 0.628,
  ),
  Glyph.fingering2: GlyphMetrics(
    box: Box(0.08, -1.012, 0.888, 0.012),
    advance: 0.968,
  ),
  Glyph.fingering3: GlyphMetrics(
    box: Box(0.08, -1.008, 0.82, 0),
    advance: 0.9,
  ),
  Glyph.fingering4: GlyphMetrics(
    box: Box(0.08, -1.012, 0.864, -0.004),
    advance: 0.944,
  ),
  Glyph.fingering5: GlyphMetrics(
    box: Box(0.08, -1.032, 0.82, 0),
    advance: 0.9,
  ),
  Glyph.fingering6: GlyphMetrics(
    box: Box(0.08, -1, 0.864, 0),
    advance: 0.948,
  ),
  Glyph.fingering7: GlyphMetrics(
    box: Box(0.08, -0.98, 0.868, 0),
    advance: 0.968,
  ),
  Glyph.fingering8: GlyphMetrics(
    box: Box(0.08, -1.004, 0.848, 0),
    advance: 0.924,
  ),
  Glyph.fingering9: GlyphMetrics(
    box: Box(0.08, -1, 0.864, 0),
    advance: 0.94,
  ),
  Glyph.guitarString0: GlyphMetrics(
    box: Box(0.004, -2.156, 2.164, 0),
    advance: 2.168,
  ),
  Glyph.guitarString1: GlyphMetrics(
    box: Box(0, -2.156, 2.16, 0),
    advance: 2.16,
  ),
  Glyph.guitarString2: GlyphMetrics(
    box: Box(0, -2.156, 2.16, 0),
    advance: 2.16,
  ),
  Glyph.guitarString3: GlyphMetrics(
    box: Box(0, -2.156, 2.16, 0),
    advance: 2.16,
  ),
  Glyph.guitarString4: GlyphMetrics(
    box: Box(0.004, -2.156, 2.164, 0),
    advance: 2.172,
  ),
  Glyph.guitarString5: GlyphMetrics(
    box: Box(0, -2.156, 2.16, 0),
    advance: 2.164,
  ),
  Glyph.guitarString6: GlyphMetrics(
    box: Box(0, -2.156, 2.16, 0),
    advance: 2.16,
  ),
  Glyph.guitarString7: GlyphMetrics(
    box: Box(0, -2.156, 2.16, 0),
    advance: 2.16,
  ),
  Glyph.guitarString8: GlyphMetrics(
    box: Box(0, -2.156, 2.16, 0),
    advance: 2.16,
  ),
  Glyph.guitarString9: GlyphMetrics(
    box: Box(0, -2.156, 2.16, 0),
    advance: 2.16,
  ),
  Glyph.keyboardPedalPed: GlyphMetrics(
    box: Box(0, -2.22, 4.076, 0.032),
    advance: 4.076,
  ),
  Glyph.keyboardPedalUp: GlyphMetrics(
    box: Box(0, -1.8, 1.8, 0),
    advance: 1.8,
  ),
  Glyph.keyboardPedalUpNotch: GlyphMetrics(
    box: Box(0, -2.128, 1.16, 0),
    advance: 1.16,
  ),
  Glyph.ottava: GlyphMetrics(
    box: Box(0, -1.852, 1.544, 0.04),
    advance: 1.544,
  ),
  Glyph.ottavaAlta: GlyphMetrics(
    box: Box(0, -1.852, 3.54, 0.04),
    advance: 3.54,
  ),
  Glyph.ottavaBassa: GlyphMetrics(
    box: Box(0, -1.852, 3.356, 0.04),
    advance: 3.356,
  ),
  Glyph.ottavaBassaBa: GlyphMetrics(
    box: Box(0, -1.852, 3.5, 0.04),
    advance: 3.5,
  ),
  Glyph.quindicesima: GlyphMetrics(
    box: Box(0, -1.844, 2.668, 0.04),
    advance: 2.668,
  ),
  Glyph.quindicesimaAlta: GlyphMetrics(
    box: Box(0, -1.844, 5.26, 0.04),
    advance: 5.26,
  ),
  Glyph.quindicesimaBassa: GlyphMetrics(
    box: Box(0, -1.844, 5.14, 0.04),
    advance: 5.14,
  ),
  Glyph.ventiduesima: GlyphMetrics(
    box: Box(0.016, -1.852, 3, 0.028),
    advance: 3,
  ),
  Glyph.ventiduesimaAlta: GlyphMetrics(
    box: Box(0.016, -1.852, 5.712, 0.028),
    advance: 5.712,
  ),
  Glyph.ventiduesimaBassa: GlyphMetrics(
    box: Box(0.016, -1.852, 5.512, 0.028),
    advance: 5.512,
  ),
  Glyph.octaveParensLeft: GlyphMetrics(
    box: Box(0, -1.94, 0.652, 0.068),
    advance: 0.548,
  ),
  Glyph.octaveParensRight: GlyphMetrics(
    box: Box(-0.104, -1.94, 0.548, 0.068),
    advance: 0.548,
  ),
  Glyph.ottavaBassaVb: GlyphMetrics(
    box: Box(0, -1.852, 3.184, 0.04),
    advance: 3.184,
  ),
  Glyph.quindicesimaBassaMb: GlyphMetrics(
    box: Box(0, -1.844, 4.928, 0.04),
    advance: 4.924,
  ),
  Glyph.ventiduesimaBassaMb: GlyphMetrics(
    box: Box(0.016, -1.852, 5.34, 0.028),
    advance: 5.34,
  ),
  Glyph.repeatLeft: GlyphMetrics(
    box: Box(0, -4, 1.464, 0),
    advance: 1.472,
  ),
  Glyph.repeatRight: GlyphMetrics(
    box: Box(0.004, -4, 1.468, 0),
    advance: 1.468,
  ),
  Glyph.repeatRightLeft: GlyphMetrics(
    box: Box(0.004, -4, 2.432, 0),
    advance: 2.432,
  ),
  Glyph.repeatDots: GlyphMetrics(
    box: Box(0, -2.68, 0.4, -1.272),
    advance: 0.4,
  ),
  Glyph.repeatDot: GlyphMetrics(
    box: Box(0, -0.2, 0.4, 0.2),
    advance: 0.4,
  ),
  Glyph.dalSegno: GlyphMetrics(
    box: Box(0.044, -1.768, 4.328, 0.036),
    advance: 4.328,
  ),
  Glyph.daCapo: GlyphMetrics(
    box: Box(0.044, -1.768, 4.328, 0.036),
    advance: 4.332,
  ),
  Glyph.segno: GlyphMetrics(
    box: Box(0.016, -3.036, 2.2, 0.108),
    advance: 2.228,
  ),
  Glyph.coda: GlyphMetrics(
    box: Box(-0.016, -3.592, 3.82, 0.632),
    advance: 3.816,
  ),
  Glyph.codaSquare: GlyphMetrics(
    box: Box(0, -3.612, 3.288, 0.616),
    advance: 3.276,
  ),
  Glyph.barlineSingle: GlyphMetrics(
    box: Box(0, -4, 0.144, 0),
    advance: 0.144,
  ),
  Glyph.barlineDouble: GlyphMetrics(
    box: Box(0, -4, 0.576, 0),
    advance: 0.576,
  ),
  Glyph.barlineFinal: GlyphMetrics(
    box: Box(0, -4, 0.912, 0),
    advance: 0.916,
  ),
  Glyph.barlineHeavy: GlyphMetrics(
    box: Box(0, -4, 0.5, 0),
    advance: 0.5,
  ),
  Glyph.barlineDashed: GlyphMetrics(
    box: Box(0, -4, 0.144, 0),
    advance: 0.144,
  ),
  Glyph.barlineDotted: GlyphMetrics(
    box: Box(0, -3.988, 0.196, 0),
    advance: 0.196,
  ),
  Glyph.brace: GlyphMetrics(
    box: Box(0.008, -3.988, 0.328, 0),
    advance: 0.336,
  ),
  Glyph.bracket: GlyphMetrics(
    box: Box(0, -5.284, 1.876, 1.272),
    advance: 2.232,
  ),
  Glyph.bracketTop: GlyphMetrics(
    box: Box(0, -1.18, 1.876, 0),
    advance: 1.876,
  ),
  Glyph.bracketBottom: GlyphMetrics(
    box: Box(0, 0, 1.876, 1.18),
    advance: 1.876,
  ),
  Glyph.legerLine: GlyphMetrics(
    box: Box(-0.32, -0.08, 1.648, 0.08),
    advance: 1.328,
  ),
  Glyph.metNoteWhole: GlyphMetrics(
    box: Box(0, -0.592, 1.836, 0.5),
    advance: 1.836,
  ),
  Glyph.metNoteHalfUp: GlyphMetrics(
    box: Box(0, -2.752, 1.364, 0.564),
    advance: 1.364,
  ),
  Glyph.metNoteQuarterUp: GlyphMetrics(
    box: Box(0, -2.752, 1.328, 0.564),
    advance: 1.328,
  ),
  Glyph.metNote8thUp: GlyphMetrics(
    box: Box(0, -2.784, 2.132, 0.564),
    advance: 2.136,
  ),
  Glyph.metNote16thUp: GlyphMetrics(
    box: Box(0, -2.8, 2.084, 0.564),
    advance: 2.088,
  ),
  Glyph.metAugmentationDot: GlyphMetrics(
    box: Box(0, -0.2, 0.4, 0.2),
    advance: 0.4,
  ),
  Glyph.csymAccidentalFlat: GlyphMetrics(
    box: Box(0.004, -3, 1.136, 0.004),
    advance: 1.136,
  ),
  Glyph.csymAccidentalSharp: GlyphMetrics(
    box: Box(0, -3.048, 1.24, 0.052),
    advance: 1.24,
  ),
};
