/// Turns Bravura's metadata into `lib/src/bravura.g.dart`.
///
/// Run from the package root with `dart run tool/generate_bravura.dart`.
/// An argument names another file to write.
///
/// The table is const Dart, so the app parses no JSON at startup. The
/// metadata is read by the reader `SmuflFont.fromMetadata` uses, so it fails
/// on the same drifts between the `Glyph` enum, `EngravingDefaults`
/// and the font.
library;

import 'dart:convert';
import 'dart:io';

import 'package:score_layout/src/geometry.dart';
import 'package:score_layout/src/smufl_metadata.dart';

const metadataPath = '../../assets/bravura_metadata.json';
const outputPath = 'lib/src/bravura.g.dart';

void main(List<String> arguments) {
  final output = arguments.firstOrNull ?? outputPath;
  final metadata =
      jsonDecode(File(metadataPath).readAsStringSync()) as Map<String, Object?>;
  final (:glyphs, :defaults) = readSmuflMetadata(metadata);

  final out = StringBuffer()
    ..writeln(
      '// GENERATED by tool/generate_bravura.dart from '
      '${metadata['fontName']} ${metadata['fontVersion']}.',
    )
    ..writeln('// Do not edit.')
    ..writeln()
    ..writeln("import 'geometry.dart';")
    ..writeln("import 'glyphs.dart';")
    ..writeln()
    ..writeln('const bravuraDefaults = EngravingDefaults(');
  for (final MapEntry(key: name, :value) in defaults.entries) {
    out.writeln('  $name: ${_number(value)},');
  }
  out
    ..writeln(');')
    ..writeln()
    ..writeln('const bravuraGlyphs = <Glyph, GlyphMetrics>{');
  for (final MapEntry(key: glyph, value: metrics) in glyphs.entries) {
    final box = metrics.box;
    out
      ..writeln('  Glyph.${glyph.name}: GlyphMetrics(')
      ..writeln(
        '    box: Box(${_number(box.left)}, ${_number(box.top)}, '
        '${_number(box.right)}, ${_number(box.bottom)}),',
      )
      ..writeln('    advance: ${_number(metrics.advance)},');
    if (metrics.anchors.isNotEmpty) {
      out.writeln('    anchors: {');
      for (final MapEntry(key: anchor, value: point)
          in metrics.anchors.entries) {
        out.writeln('      GlyphAnchor.${anchor.name}: ${_point(point)},');
      }
      out.writeln('    },');
    }
    out.writeln('  ),');
  }
  out.writeln('};');
  File(output).writeAsStringSync(out.toString());
  // The formatter owns line breaks, so a rerun leaves a formatted tree
  // formatted.
  final format = Process.runSync(Platform.resolvedExecutable, [
    'format',
    output,
  ]);
  if (format.exitCode != 0) {
    throw StateError('dart format failed: ${format.stderr}');
  }
  stdout.writeln('wrote $output: ${glyphs.length} glyphs');
}

String _point(SpPoint point) => point == SpPoint.zero
    ? 'SpPoint.zero'
    : 'SpPoint(${_number(point.x)}, ${_number(point.y)})';

/// An int literal for a whole value, else the double, so the table satisfies
/// the same lints as hand-written code.
String _number(double value) =>
    value == value.roundToDouble() ? value.toInt().toString() : '$value';
