/// Turns `assets/bravura_metadata.json` into `lib/src/bravura.g.dart`.
///
/// Run from the package root with `dart run tool/generate_bravura.dart`.
///
/// The table is const Dart, so the app parses no JSON at startup. Y is
/// flipped here, once, into the y-down layout frame. The script fails when
/// a `Glyph` has no box, when a `Glyph` has no advance, when a glyph carries
/// an anchor `GlyphAnchor` lacks, or when the numeric engraving defaults do
/// not match `EngravingDefaults` field for field. So the enum, the class
/// and the font cannot drift apart silently.
///
/// In the implementation the metadata sits beside the engine and
/// [metadataPath] shortens with it.
library;

import 'dart:convert';
import 'dart:io';

import 'package:score_layout/src/glyphs.dart';

const metadataPath = '../../../../../assets/bravura_metadata.json';
const outputPath = 'lib/src/bravura.g.dart';

/// The fields of `EngravingDefaults`, in its order. Dart has no reflection
/// here, so the list is repeated. A name that is not a field makes the
/// generated file fail to compile, and a field that is not listed makes it
/// fail on a missing required argument.
const engravingFields = [
  'arrowShaftThickness',
  'barlineSeparation',
  'beamSpacing',
  'beamThickness',
  'bracketThickness',
  'dashedBarlineDashLength',
  'dashedBarlineGapLength',
  'dashedBarlineThickness',
  'hBarThickness',
  'hairpinThickness',
  'legerLineExtension',
  'legerLineThickness',
  'lyricLineThickness',
  'octaveLineThickness',
  'pedalLineThickness',
  'repeatBarlineDotSeparation',
  'repeatEndingLineThickness',
  'slurEndpointThickness',
  'slurMidpointThickness',
  'staffLineThickness',
  'stemThickness',
  'subBracketThickness',
  'textEnclosureThickness',
  'thickBarlineThickness',
  'thinBarlineThickness',
  'tieEndpointThickness',
  'tieMidpointThickness',
  'tupletBracketThickness',
];

void main() {
  final metadata =
      jsonDecode(File(metadataPath).readAsStringSync()) as Map<String, Object?>;
  final name = metadata['fontName']! as String;
  final version = '${metadata['fontVersion']}';
  final engraving = metadata['engravingDefaults']! as Map<String, Object?>;
  final boxes = metadata['glyphBBoxes']! as Map<String, Object?>;
  final advances = metadata['glyphAdvanceWidths']! as Map<String, Object?>;
  final anchors = metadata['glyphsWithAnchors']! as Map<String, Object?>;

  final numericDefaults = {
    for (final entry in engraving.entries)
      if (entry.value is num) entry.key,
  };
  final unknown = numericDefaults.difference(engravingFields.toSet());
  final missing = engravingFields.toSet().difference(numericDefaults);
  if (unknown.isNotEmpty || missing.isNotEmpty) {
    throw StateError(
      'engraving defaults drift: unknown $unknown, missing $missing',
    );
  }

  final anchorNames = {for (final anchor in GlyphAnchor.values) anchor.name};
  final out = StringBuffer()
    ..writeln('// GENERATED by tool/generate_bravura.dart from $name $version.')
    ..writeln('// Do not edit.')
    ..writeln()
    ..writeln("import 'geometry.dart';")
    ..writeln("import 'glyphs.dart';")
    ..writeln()
    ..writeln('const bravuraDefaults = EngravingDefaults(');
  for (final field in engravingFields) {
    out.writeln('  $field: ${_number(engraving[field])},');
  }
  out
    ..writeln(');')
    ..writeln()
    ..writeln('const bravuraGlyphs = <Glyph, GlyphMetrics>{');
  for (final glyph in Glyph.values) {
    final box = boxes[glyph.name] as Map<String, Object?>?;
    final advance = advances[glyph.name];
    if (box == null) {
      throw StateError('${glyph.name} has no box in $name');
    }
    if (advance == null) {
      throw StateError('${glyph.name} has no advance in $name');
    }
    final ne = (box['bBoxNE']! as List<Object?>).cast<num>();
    final sw = (box['bBoxSW']! as List<Object?>).cast<num>();
    out
      ..writeln('  Glyph.${glyph.name}: GlyphMetrics(')
      ..writeln(
        '    box: Box(${_number(sw[0])}, ${_number(-ne[1])}, '
        '${_number(ne[0])}, ${_number(-sw[1])}),',
      )
      ..writeln('    advance: ${_number(advance)},');
    final glyphAnchors = anchors[glyph.name] as Map<String, Object?>?;
    if (glyphAnchors != null) {
      out.writeln('    anchors: {');
      for (final entry in glyphAnchors.entries) {
        if (!anchorNames.contains(entry.key)) {
          throw StateError(
            '${glyph.name} has anchor ${entry.key}, not in GlyphAnchor',
          );
        }
        final point = (entry.value! as List<Object?>).cast<num>();
        out.writeln('      GlyphAnchor.${entry.key}: ${_point(point)},');
      }
      out.writeln('    },');
    }
    out.writeln('  ),');
  }
  out.writeln('};');
  File(outputPath).writeAsStringSync(out.toString());
  // The formatter owns line breaks, so a rerun leaves a formatted tree
  // formatted.
  final format = Process.runSync(Platform.resolvedExecutable, [
    'format',
    outputPath,
  ]);
  if (format.exitCode != 0) {
    throw StateError('dart format failed: ${format.stderr}');
  }
  stdout.writeln('wrote $outputPath: ${Glyph.values.length} glyphs');
}

String _point(List<num> xy) => xy[0] == 0 && xy[1] == 0
    ? 'SpPoint.zero'
    : 'SpPoint(${_number(xy[0])}, ${_number(-xy[1])})';

/// An int literal for an integral value, else the double, so the table
/// satisfies the same lints as hand-written code.
String _number(Object? value) {
  final n = (value! as num).toDouble();
  if (n == 0) {
    return '0';
  }
  return n == n.roundToDouble() ? n.toInt().toString() : n.toString();
}
